# Each page blueprint must have a title, the title may be different from the file name
title: Product

# Each page can have an icon that is shown in page listings when no preview image is available.
icon: ☎️

# Limit the possible page statuses to `draft` and `listed`.
# More about page statuses: https://getkirby.com/docs/reference/panel/blueprints/page#statuses
status:
  draft: true
  listed: true


# Page options allow you to control how users can interact with the page.
# Here we prevent changing the page slug and page deletion
# More about page options: https://getkirby.com/docs/reference/panel/blueprints/page#options
options:
  changeSlug: true
  delete: true

columns:
  - width: 1/2
    fields:
      text:
        label: Text
        type: textarea
        size: huge

  - width: 1/2

    fields:
      imageupload:
        label: Imagens
        type: files
