# The site blueprint must have a title, the title may be different from the file name
# The `site.yml` blueprint defines the look of the start page (Dashboard) of the Panel.
title: Site

# The site blueprint usually provides easy access to all main pages of the site.
# In this example blueprint, we also show subpages of the `photography` and `notes` pages.
# More about the site blueprint: https://getkirby.com/docs/reference/panel/blueprints/site

# The layout of this form has two columns:
columns:
  # The first column has one section for the subpages of the `photography` page in card layout
  # It reuses the pages section defined in `/site/blueprints/sections/albums.yml`
  # The second column has two sections, `notes` and `pages`

  - width: 1/2
    fields:
      descr:
        type: textarea
        size: medium
        label: Description
        help: Main Site description for Indexing purposes
      talk:
        label: Main Contact form
        type: email
        help: main contact email to show on menu
      stalk:
        type: url
        label: Stalk
        help: main social media link
      line:
        type: line

  - width: 1/2
    sections:
      pages:
        type: pages

  - width: 1/2
    sections:
      files:
        label: Imagens
        type: files
        help: Site wide files or images, good for temporary download links and so on